name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      env:
        HEROKU_API: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'classificados-api' }}
        HEROKU_USER: ${{ 'mandeemailpramim@gmail.com' }}
      run: | 
        cd ./
        docker login --username=$HEROKU_USER --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
